# Generated by Django 4.2.3 on 2023-07-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_todomodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='note',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='task_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='task_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
