# Generated by Django 4.2.3 on 2023-07-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_todomodel_note_todomodel_task_en_todomodel_task_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='note_en',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='note_uz',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
